services:

  rosbot:
    # image: rosbot-local
    build:
      context: ../../
      dockerfile: Dockerfile
      # dockerfile: Dockerfile.hardware
    network_mode: host
    ipc: host
    devices:
      - ${SERIAL_PORT:?err}
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/shm-only.xml
    command: >
      ros2 launch rosbot_bringup combined.launch.py 
        mecanum:=${MECANUM:-False}
        serial_port:=$SERIAL_PORT 
        serial_baudrate:=576000
        namespace:=robot1

  ros2router:
    image: husarnet/ros2router:release-1.4.0
    network_mode: host
    ipc: host
    volumes:
      - ./filter.yaml:/filter.yaml
    environment:
      - USE_HUSARNET=FALSE
      - ROS_LOCALHOST_ONLY=1
      - ROS_DISTRO

# 1. run `docker-compose up` on the robot
# 2. On the second host in LAN you will see only single ros2 topic:
#   $ ros2 topic list
#   /parameter_events
#   /robot1/cmd_vel
#   /rosout
# 3. You can use teleop_twist_keyboard to control the robot in robot1 namespace:
# `ros2 run teleop_twist_keyboard teleop_twist_keyboard  --ros-args -r __ns:=/robot1`