# Quick Start
# $ docker compose -f compose.minimal.yaml up

services:

  bridge:
    image: husarion/ros:eloquent-ros1-bridge
    restart: unless-stopped
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
      - ROS_DOMAIN_ID
      - RMW_IMPLEMENTATION
    command: ros2 run ros1_bridge dynamic_bridge --bridge-all-1to2-topics

  ros-master:
    image: ros:melodic-ros-core
    restart: unless-stopped
    tty: true
    command: roscore

  rosbot:
    image: husarion/rosbot:melodic
    container_name: rosbot
    restart: unless-stopped
    tty: true
    devices:
      - ${SERIAL_PORT}
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
      - SERIAL_PORT
    command: roslaunch --wait rosbot_bringup rosbot_docker.launch