# Quick Start
# $ xhost local:root
# $ docker compose -f compose.rviz.yaml -f compose.rviz.lan.yaml up

services:

  rviz:
    network_mode: host
    ipc: host
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
