# Quick Start
# $ docker compose -f compose.rosbot.simulation.yaml -f compose.rosbot.mapping.yaml up

services:

  bridge:
    image: husarion/ros:galactic-ros1-bridge
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
    command: ros2 run ros1_bridge dynamic_bridge

  ros-master:
    image: ros:noetic-ros-core
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
    command: stdbuf -o L roscore

  rosbot_simulation:
    image: husarion/rosbot:noetic-simulation
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1
      - ROS_MASTER_URI=http://ros-master:11311
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      roslaunch --wait rosbot_bringup rosbot.launch
        world:=/ros_ws/src/rosbot_gazebo/worlds/maze.world
