# Quick Start
#
# 1. run `docker compose up` on the robot
# 2. run `ROS_DOMAIN_ID=10 ros2 run teleop_twist_keyboard teleop_twist_keyboard` in the robot terminal

services:

  rosbot:
    image: husarion/rosbot:humble-0.10.3-20231128
    environment:
      - ROS_DOMAIN_ID=10
    command: ros2 launch rosbot_bringup bringup.launch.py mecanum:=${MECANUM:-False}

  micro-ros-agent:
    image: husarion/micro-ros-agent:humble-3.1.3-20231122
    devices:
      - ${SERIAL_PORT:?err}
    environment:
      - ROS_DOMAIN_ID=10
    command: ros2 run micro_ros_agent micro_ros_agent serial -D $SERIAL_PORT serial -b 576000 # -v6
