# Quick Start
# $ docker compose -f compose.rosbot.hardware.yaml up

services:

  rplidar:
    image: husarion/rplidar:humble
    restart: unless-stopped
    devices:
      - /dev/ttyUSB0
    command: >
        ros2 launch sllidar_ros2 sllidar_launch.py
        serial_baudrate:=${RPLIDAR_BAUDRATE:-115200}
        frame_id:=lidar_link

  microros:
    image: microros/micro-ros-agent:humble
    restart: unless-stopped
    command: serial -D ${SERIAL_PORT:-/dev/ttyAMA0}  serial -b 576000 # -v6
    devices:
      - ${SERIAL_PORT:-/dev/ttyAMA0}

  rosbot:
    image: husarion/rosbot:humble
    restart: unless-stopped
    command: >
      ros2 launch rosbot_bringup rosbot_bringup.launch.py