# Quick Start
# $ xhost local:root
# $ docker compose -f compose.rviz.yaml up

services:

  # ROS Galactic
  rviz:
    image: husarion/rviz2:galactic
    container_name: rviz
    restart: on-failure
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # - ./config/rosbot_mapping.rviz:/root/.rviz2/default.rviz
      - ./config/rosbot_localization.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
