# Quick Start
# $ xhost local:root
# $ docker compose -f compose.rviz.yaml -f compose.rviz.vpn.yaml up

services:

  rviz:
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=1
    ipc: host

  dds-router:
    image: husarnet/dds-router:experimental
    network_mode: host
    ipc: host
    volumes:
      - ./router-config.client.yaml:/config.yaml
    command: ddsrouter -c /config.yaml -r 10 -d