# Quick Start
# $ docker compose -f compose.rosbot.hardware.yaml -f compose.rosbot.lan.yaml up

services:

  localization-mapping:
    network_mode: host
    ipc: host
    environment:
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}

  navigation:
    network_mode: host
    ipc: host
    environment:
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}

  rplidar:
    network_mode: host
    ipc: host
    environment:
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}

  microros:
    network_mode: host
    ipc: host
    environment:
    - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}

  rosbot:
    network_mode: host
    ipc: host
    environment:
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}