# Quick Start (at fist stop ROS Master if working on host)
# $ docker compose -f compose.rosbot.hardware.yaml -f compose.rosbot.vpn.yaml up

services:

  localization-mapping:
    network_mode: host
    ipc: host
    volumes:
      - ./dds-config.client.xml:/dds-config.xml
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp

  navigation:
    network_mode: host
    ipc: host
    volumes:
      - ./dds-config.client.xml:/dds-config.xml
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp

  discovery-server:
    network_mode: host
    ipc: host
    image: ros:humble-ros-core
    command: fast-discovery-server -x /dds-config.xml
    volumes:
      - ./dds-config.server.xml:/dds-config.xml
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp

  rplidar:
    network_mode: host
    ipc: host
    volumes:
      - ./dds-config.client.xml:/dds-config.xml
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp


  microros:
    network_mode: host
    ipc: host
    volumes:
      - ./dds-config.client.xml:/dds-config.xml
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp

  rosbot:
    network_mode: host
    ipc: host
    volumes:
      - ./dds-config.client.xml:/dds-config.xml
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
