# Quick Start
# $ docker compose -f compose.flash-firmware.yaml up

services:

  flash-fw:
    image: husarion/rosbot:humble
    privileged: true
    environment:
      - SERIAL_PORT=${SERIAL_PORT:?err}
    devices:
      - ${SERIAL_PORT}
    command: /flash-firmware.py /root/firmware.bin
