# Quick Start
# 
# 1. run `xhost +local:docker && docker compose -f compose.gazebo.yaml up` on the laptop
# 2. open a shell inside a docker container `docker compose -f compose.gazebo.yaml exec -it rosbot bash`
# 2. run `ros2 run teleop_twist_keyboard teleop_twist_keyboard` inside the container

x-gpu-config:
  &gpu-config
  runtime: nvidia
  environment:
    - DISPLAY=${DISPLAY:?err}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all

x-cpu-config:
  &cpu-config
  environment:
    - DISPLAY=${DISPLAY:?err}
    - LIBGL_ALWAYS_SOFTWARE=1

services:
  rosbot:
    # image: husarion/rosbot-gazebo:humble
    build:
      context: ../
      dockerfile: Dockerfile.gazebo
    <<: [ *gpu-config]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: ros2 launch rosbot_gazebo simulation.launch.py mecanum:=${MECANUM:-False}
