version: v2.0

builtin:
  # - name: "rt/chatter"
  #   type: "std_msgs::msg::dds_::String_"

allowlist:
  - name: "*"
  # - name: "rt/chatter"
  #   type: "std_msgs::msg::dds_::String_"
  # - name: "rt/scan"
  #   type: "sensor_msgs::msg::dds_::LaserScan_"

participants:
  
  - name: LocalParticipant
    kind: local
    domain: 0

  - name: ServerWAN
    kind: local-discovery-server
    discovery-server-guid:
      ros-discovery-server: true
      id: 1
    listening-addresses:
      - domain: rosbot2r
        port: 11811
        transport: udp
