version: v2.0

threads: 50

builtin:
  # - name: "rt/scan"
  #   type: "sensor_msgs::msg::dds_::LaserScan_"
  # - name: "rt/chatter"
  #   type: "std_msgs::msg::dds_::String_"
  # - name: "rt/scan"
  #   type: "sensor_msgs::msg::dds_::LaserScan_"

allowlist:
  - name: "*"
  # - name: "rt/scan"
  #   type: "sensor_msgs::msg::dds_::LaserScan_"

  # - name: "rt/chatter"
  #   type: "std_msgs::msg::dds_::String_"
  # - name: "rt/scan"
  #   type: "sensor_msgs::msg::dds_::LaserScan_"

participants:
  
  - name: LocalParticipant
    kind: local
    domain: 1

  # - name: ClientWAN
  #   kind: discovery-server
  #   discovery-server-guid:
  #     ros-discovery-server: true
  #     id: 2
  #   connection-addresses:
  #     - discovery-server-guid:
  #         ros-discovery-server: true
  #         id: 1
  #       addresses:
  #         - domain: rosbot2r
  #           port: 11811
  #           transport: udp

  - name: ClientWAN
    kind: discovery-server
    discovery-server-guid:
      ros-discovery-server: true
      id: 2
    connection-addresses:
      - discovery-server-guid:
          ros-discovery-server: true
          id: 1
        addresses:
          - domain: rosbot2r
            port: 11811
            transport: udp
    listening-addresses:
      - domain: legion-y540
        port: 11811
        transport: udp