services:

  rviz:
    image: husarion/rviz2:galactic
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1
    command: ros2 run rviz2 rviz2 -d /settings/rosbot2-nav2-demo.rviz

  navigation:
    image: husarion/navigation2:galactic
    command: >
      ros2 launch nav2_bringup navigation_launch.py    
        params_file:=/nav2_params/rosbot2_navigation.yaml
        use_sim_time:=True

  mapping:
    image: husarion/slam-toolbox:galactic
    command: >
      ros2 launch slam_toolbox online_sync_launch.py
        slam_params_file:=/slam_params/rosbot2.yaml
        use_sim_time:=True

  bridge:
    image: husarion/ros:galactic-ros1-bridge
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
    command: ros2 run ros1_bridge dynamic_bridge

  ros-master:
    image: ros:noetic-ros-core
    # environment:
    #   - ROS_MASTER_URI=http://ros-master:11311
    command: stdbuf -o L roscore

  rosbot_simulation:
    image: husarion/rosbot:noetic-simulation
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1
      - ROS_MASTER_URI=http://ros-master:11311
    command: >
      roslaunch --wait rosbot_bringup rosbot.launch 
        world:=/ros_ws/src/rosbot_gazebo/worlds/maze.world
