name: Docker image for hardware

on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: [ros-package-update]
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros-distro: humble
            rosbot-fw-release: "0.2.0"
            platforms: "linux/amd64, linux/arm64"

    steps:

    - name: Print event name
      run: echo "Event name ${{ github.event_name }}"
  
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest

    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Print branch name
      run: echo ${{ github.ref_name}}

    - name: Set SHORT_DATE env
      run: echo "SHORT_DATE=$(date +%y-%m-%d)" >> $GITHUB_ENV

    - name: Build and push (production)
      if: github.ref_name == 'ros2'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.hardware
        platforms: ${{ matrix.platforms }}
        push: true
        build-args: |
          ROS_DISTRO=${{ matrix.ros-distro }}
          ROSBOT_FW_RELEASE=${{ matrix.rosbot-fw-release }}
        tags: |
          husarion/rosbot:${{ matrix.ros-distro }}
          husarion/rosbot:${{ matrix.ros-distro }}-${{ env.SHORT_DATE }}
        # cache-from: type=registry,ref=husarion/rosbot:${{ matrix.ros-distro }}
        # cache-to: type=inline

    - name: Build and push (development)
      if: github.ref_name != 'ros2'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.hardware
        platforms: ${{ matrix.platforms }}
        push: true
        build-args: |
          ROS_DISTRO=${{ matrix.ros-distro }}
          ROSBOT_FW_RELEASE=${{ matrix.rosbot-fw-release }}
        tags: husarion/rosbot:${{ matrix.ros-distro }}-${{ github.head_ref || github.ref_name }}
        # cache-from: type=registry,ref=husarion/rosbot:${{ matrix.ros-distro }}-${{ github.head_ref || github.ref_name }}
        # cache-to: type=inline